package(default_visibility = ["//util:__subpackages__"])

load("@com_github_google_flatbuffers//:build_defs.bzl", "flatbuffer_cc_library")

flatbuffer_cc_library(
    name = "test",
    srcs = ["test.fbs"],
)
