package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "generate-embed-data",
    srcs = ["generate-embed-data.cc"],
    deps = [
        "//base:flags",
        "//base:logging",
        "//io:file-utils",
        "//io:native-file",
        "//io:stream",
    ],
)
