package(default_visibility = ["//visibility:public"])

cc_library(
    name = "logging",
    srcs = ["logging.cc"],
    hdrs = ["logging.h"],
    deps = ["@org_boost_boost//:log"],
)

cc_library(
    name = "packed",
    hdrs = ["packed.h"],
)
