name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: mount bazel cache
      uses: actions/cache@v3
      with:
        key: bazel
        path: ~/.cache/bazel
    - name: install bazel
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        curl -fLo "${GITHUB_WORKSPACE}/bin/bazel" "https://github.com/bazelbuild/bazel/releases/download/6.5.0/bazel-6.5.0-linux-x86_64"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
    - name: test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test ...
